"""Add campaign_name to facebook_config

Revision ID: 880d575397d4
Revises: 
Create Date: 2024-11-12 02:08:07.632713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '880d575397d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facebook_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campaign_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facebook_config', schema=None) as batch_op:
        batch_op.drop_column('campaign_name')

    # ### end Alembic commands ###
