"""Add pixel_id to ClickData

Revision ID: e89e4df3a087
Revises: 880d575397d4
Create Date: 2024-11-14 23:43:39.866975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e89e4df3a087'
down_revision = '880d575397d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('click_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pixel_id', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('click_data', schema=None) as batch_op:
        batch_op.drop_column('pixel_id')

    # ### end Alembic commands ###
